WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

ORIGINAL_TILE_SIZE = 20
TILE_SIZE = 40
PLAYER_HEIGHT = 2 * TILE_SIZE

HALF_WIDTH = WINDOW_WIDTH // 2
HALF_HEIGHT = WINDOW_HEIGHT // 2 - PLAYER_HEIGHT

# Game Physics
G = 2.2

# Debug
ENABLE_CAMERA_SCROLL = True
